//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetMe.Data.Remote
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecord
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int AppointmentId { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
