//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetMe.Data.Remote
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeterinaryClinicEntities : DbContext
    {
        public VeterinaryClinicEntities()
            : base("name=VeterinaryClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<MedicalRecord> MedicalRecords { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<PetGender> PetGenders { get; set; }
        public virtual DbSet<Specialty> Specialties { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<Vet> Vets { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
